//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazzor.Data
{
    using System;
    
    public partial class TrailMap_RawResult
    {
        public string Title { get; set; }
        public Nullable<long> Scale { get; set; }
        public string URL { get; set; }
    }
}
