//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazzor.Data
{
    using System;
    
    public partial class Trail_RawResult
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<int> Difficulty_Level { get; set; }
        public string Difficulty_Name { get; set; }
        public string City_From { get; set; }
        public string City_From_Path { get; set; }
        public string Season { get; set; }
        public long Length { get; set; }
        public Nullable<long> Duration { get; set; }
        public string Description { get; set; }
        public string Guide { get; set; }
        public string SOSService { get; set; }
        public long ID { get; set; }
        public string KmlPath { get; set; }
        public string ElevationProfile { get; set; }
        public string StreetViewURL { get; set; }
        public string VirtualTour { get; set; }
    }
}
