//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazzor.Data
{
    using System;
    
    public partial class TrailImage_RawResult
    {
        public long Id { get; set; }
        public Nullable<long> Id_Trail { get; set; }
        public string ImageUrl { get; set; }
    }
}
